---
all:
  children:
    vcenter:
      hosts:
        vcsa01:
          ansible_host: vcsa.example.com

  vars:
    ansible_user: administrator@vsphere.local
    ansible_password: VMware123!
    validate_certs: false
