---
- name: Create VMware Folder
  hosts: vcenter
  gather_facts: false

  tasks:

    - name: Create VM Folder
      community.vmware.vcenter_folder:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter_name: "{{ datacenter_name }}"
        folder_name: "{{ folder_name }}"
        folder_type: vm
        state: present
