---
- name: Delete VMware Snapshot
  hosts: vcenter
  gather_facts: false

  tasks:
    - name: Remove VM Snapshot
      community.vmware.vmware_guest_snapshot:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: absent
        snapshot_name: "{{ snapshot_name }}"
